# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/DbView.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DbView(object):
    def setupUi(self, DbView):
        DbView.setObjectName("DbView")
        DbView.resize(705, 620)
        self.dbView = QtWidgets.QTableView(DbView)
        self.dbView.setGeometry(QtCore.QRect(20, 31, 461, 521))
        self.dbView.setObjectName("dbView")
        self.helper = QtWidgets.QLabel(DbView)
        self.helper.setGeometry(QtCore.QRect(510, 220, 131, 81))
        self.helper.setWordWrap(True)
        self.helper.setObjectName("helper")
        self.verticalLayoutWidget = QtWidgets.QWidget(DbView)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 100, 131, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connectMongo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.connectMongo.setObjectName("connectMongo")
        self.verticalLayout.addWidget(self.connectMongo)
        self.CreateItem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CreateItem.setObjectName("CreateItem")
        self.verticalLayout.addWidget(self.CreateItem)
        self.connectStatus = QtWidgets.QLabel(DbView)
        self.connectStatus.setGeometry(QtCore.QRect(511, 191, 131, 16))
        self.connectStatus.setText("")
        self.connectStatus.setObjectName("connectStatus")

        self.retranslateUi(DbView)
        QtCore.QMetaObject.connectSlotsByName(DbView)

    def retranslateUi(self, DbView):
        _translate = QtCore.QCoreApplication.translate
        DbView.setWindowTitle(_translate("DbView", "Dialog"))
        self.helper.setText(_translate("DbView", "Right Click Item Code to Edit"))
        self.connectMongo.setText(_translate("DbView", "Connect"))
        self.CreateItem.setText(_translate("DbView", "New"))
